---
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  sidePanelWidth: 0.25
  nerdFontsVersion: "3"
  border: "rounded"
  theme:
    activeBorderColor:
      - "#ebbcba"
      - "bold"
    inactiveBorderColor:
      - "#524f67"
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#403d52"
    cherryPickedCommitBgColor:
      - "#1f1d2e"
    cherryPickedCommitFgColor:
      - "#31748f"
    unstagedChangesColor:
      - "#ebbcba"
    defaultFgColor:
      - "#e0def4"
    searchingActiveBorderColor:
      - "#f6c177"
  authorColors:
    '*': "#c4a7e7"


git:
  pagers:
    - colorArg: "always"
      pager: "delta --dark --paging=never --side-by-side --syntax-theme='Catppuccin Mocha'"
  log:
    showGraph: "always"


os:
  editPreset: "nvim"
