---
# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  sidePanelWidth: 0.25
  nerdFontsVersion: "3"
  border: "rounded"
  theme:
    activeBorderColor:
      - "#ebbcba"
      - "bold"
    inactiveBorderColor:
      - "#524f67"
    optionsTextColor:
      - "#9ccfd8"
    selectedLineBgColor:
      - "#403d52"
    cherryPickedCommitBgColor:
      - "#1f1d2e"
    cherryPickedCommitFgColor:
      - "#31748f"
    unstagedChangesColor:
      - "#ebbcba"
    defaultFgColor:
      - "#e0def4"
    searchingActiveBorderColor:
      - "#f6c177"
  authorColors:
    '*': "#c4a7e7"


git:
  pagers:
    - colorArg: "always"
      pager: "delta --dark --paging=never --side-by-side --syntax-theme='Catppuccin Mocha'"
  log:
    showGraph: "always"


customCommands:
  - key: "C"
    context: "files"
    description: "Generate commit message with Claude Code"
    command: "git diff --staged | claude -p 'Generate a concise git commit message for the staged changes, following the conventional\
      \ commit format. Your response should strictly consist of the raw commit message without any markdown elements, code\
      \ blocks, backticks, or explanations. Aim for clarity and brevity, capturing the essence of the changes made without\
      \ detailing every single modification.' --model haiku --output-format text > /tmp/commit_msg && GIT_EDITOR=nvim git\
      \ commit -e -F /tmp/commit_msg"
    output: "terminal"


os:
  editPreset: "nvim"
